name: Main

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    container:
      image: crystallang/crystal
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: shards install
    - name: Build
      run: crystal build -Dpreview_mt --error-trace --release src/cve-api.cr
      id: build
